// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-KqsiN3xW6XUjWRpinJZMqDMwi0aumlA',
    appId: '1:166810882548:web:46cbb1f56ee329298769a1',
    messagingSenderId: '166810882548',
    projectId: 'myfield01',
    authDomain: 'myfield01.firebaseapp.com',
    storageBucket: 'myfield01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUG7x-zh-frmHPM5F80bIkV8vj3j0DMRU',
    appId: '1:166810882548:android:f0540bac016575988769a1',
    messagingSenderId: '166810882548',
    projectId: 'myfield01',
    storageBucket: 'myfield01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEWH83UiGC5Mwp7eqdn5oEgYqPLh6vok0',
    appId: '1:166810882548:ios:5e9c3856d0438aa18769a1',
    messagingSenderId: '166810882548',
    projectId: 'myfield01',
    storageBucket: 'myfield01.firebasestorage.app',
    iosBundleId: 'com.wildan.myfield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEWH83UiGC5Mwp7eqdn5oEgYqPLh6vok0',
    appId: '1:166810882548:ios:5e9c3856d0438aa18769a1',
    messagingSenderId: '166810882548',
    projectId: 'myfield01',
    storageBucket: 'myfield01.firebasestorage.app',
    iosBundleId: 'com.wildan.myfield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-KqsiN3xW6XUjWRpinJZMqDMwi0aumlA',
    appId: '1:166810882548:web:055ec4ba1a4f7f708769a1',
    messagingSenderId: '166810882548',
    projectId: 'myfield01',
    authDomain: 'myfield01.firebaseapp.com',
    storageBucket: 'myfield01.firebasestorage.app',
  );
}
